# Default volume level.
--volume=44

# Loop the playing file infinitely.
--loop-file='inf'

# Displayed a static image indefinitely.
--image-display-duration='inf'

# Hardware accelerated video playback.
--vo=gpu-next