{ config, lib, pkgs, ... }: {
	# The path to the user's shell.
	users.users.${config.userName}.shell = lib.mkIf config.programs.fish.enable pkgs.fish;

	# Disable man pages caching generation for FISH if taking too long on rebuilds.
	documentation.man.cache.enable = lib.mkIf config.programs.fish.enable false;

	programs.fish = {
		# Whether to configure FISH as an interactive shell.
		enable = true;

		# Set of basic shell abbreviations.
		shellAbbrs = rec {
			# Short abbreviations.
			c = "clear";
			x = "exit";

			# Finding text in a directory.
			fdtext = ''grep -Rn -e'';

			# Safer file copying.
			cp = "cp -v -i";
			copy = cp;

			# Safer directory copying.
			cpdir = "cp -r -v -i";
			copy-directory = cpdir;

			# Safer moving of files.
			mv = "mv -v -i";
			move = mv;

			# Safer file deletion.
			rm = "rm -v -i";
			remove = rm;

			# Safer directory deletion.
			rmdir = "rm -d -r -v -i";
			remove-directory = rmdir;

			# Going back more directories.
			"..." = "cd ../../";
			".3" = "cd ../../";
			"...." = "cd ../../../";
			".4" = "cd ../../../";
			"....." = "cd ../../../../";
			".5" = "cd ../../../../";
			"......" = "cd ../../../../../";
			".6" = "cd ../../../../../";

			# See what process systemd had to kill after a 1m30 timeout.
			killed = "journalctl -b-1 | grep killed";

			# Backup user files. Change the backup directory as needed.
			backup = ''rsync -av --progress -h --delete --delete-excluded --exclude-from="${config.users.users.${config.userName}.home}/.exclude.txt" ${config.users.users.${config.userName}.home}/ /run/media/${config.userName}/160GB-HDD/Backups-home/'';

			reverse-backup = ''rsync -av --progress -h /run/media/${config.userName}/160GB-HDD/Backups-home/ ${config.users.users.${config.userName}.home}/'';

			# Toggling recent files.
			enable-recent-files = "run0 rm -v -i ~/.local/share/recently-used.xbel";
			disable-recent-files = "run0 rm -v -i ~/.local/share/recently-used.xbel; touch ~/.local/share/recently-used.xbel && run0 chattr -V +i ~/.local/share/recently-used.xbel";

			# NixOS.
			channel-list = "run0 nix-channel --list";
			channel-change = "run0 nix-channel --add https://channels.nixos.org/nixos-XX.XX nixos && micro /etc/nixos/User/Home-Manager.nix";
			nix-list = "run0 nixos-rebuild list-generations";
			nix-clean = "run0 nix-collect-garbage -d --quiet --log-format bar-with-logs";
			nix-test = ''set -x CURRENTDIR $(pwd) && cd /tmp/ && run0 nixos-rebuild test --quiet --log-format bar-with-logs; cd "$CURRENTDIR"'';
			nix-update-now = "run0 nixos-rebuild switch --quiet --log-format bar-with-logs";
			nix-update-boot = "run0 nixos-rebuild boot --quiet --log-format bar-with-logs";
			nix-upgrade-now = "run0 nixos-rebuild switch --upgrade --quiet --log-format bar-with-logs";
			nix-upgrade-boot = "run0 nixos-rebuild boot --upgrade --quiet --log-format bar-with-logs";

			# Create a NixOS `.iso` file from a valid configuration.
			mknixiso = "run0 nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=configuration.nix --quiet --log-format bar-with-logs";

			# Delete an unused NixOS `.iso` generated by the command above.
			rmnixiso = "run0 nix-store --delete --ignore-liveness /nix/store/name-of-the-iso-here-linux.iso";

			# Download the latest stable NixOS `.iso` image (graphical and minimal).
			downloadnix = ''wget -v "https://channels.nixos.org/nixos-unstable/latest-nixos-graphical-x86_64-linux.iso"'';
			downloadminix = ''wget -v "https://channels.nixos.org/nixos-unstable/latest-nixos-minimal-x86_64-linux.iso"'';

			# Writing an `.iso` file to a drive.
			writeiso = "run0 dd bs=4M if=/path/to/file.iso of=/path/to/drive conv=fsync oflag=direct status=progress";

			# Creating an `.iso` file from a physical media.
			mkiso = "dd if=/dev/cdrom of=/path/to/the-iso.iso bs=4M status=progress";

			# Creating an `.iso` file from a file or directory.
			mkisofromfile = "mkisofs -lJR -o output.iso";
		};
	};

	# Link the configuration file of the FISH shell.
	systemd.user.tmpfiles.users.${config.userName}.rules = lib.optional config.programs.fish.enable
	"L %h/.config/fish/config.fish - - - - /etc/nixos/files/config.fish";
}
